### ISSUE TITLE
Please provide payment for the order on order success response

### ISSUE THREAD

**Issue by vikasebizon** [PayGate/PayWeb_Magento_2#12]
Hello, 
We are getting error on paygate success redirect page "Please provide payment for the order".
pagegate success response redirect to checkout cart page not order success page.
We are using magento 2.3.4. 
Let me know if you want any information from our side.

**Comment by RBAtkins0n** [comment]
@vikasebizon, kindly report this issue to the support team at supportsa@dpogroup.com.

The team will run through config and profile settings and then escalate the issue if they are unable to resolve the issue.
