### ISSUE TITLE
Paygate Web isssue on Magento 2.3.3 

### ISSUE THREAD

**Issue by devtactical** [PayGate/PayWeb_Magento_2#13]
We have tried integrating the Pay web Magento plugin. We are successfully redirected to paygate page on checkout, but while redirecting back to our website we are redirected to the home page with an error "Invalid Form Key. Please refresh the page and try again."

go to portal
Add the product to the cart.
Select a country, province, and enter the south African Pincode. eg. South Africa, Gauteng, 2198.
Select Anyone Shipping Method.
Click on "Go To Checkout".
Enter Address and phone number.
Click on Next at button.
Select Paygate and click on "Place order"
Enter Test Credit Card Number as below
4000000000000002, Select any future expiry date and 123 as CVV
Click Next
Click ok in alert and submit.
On submission, the Magento takes back to the home page with the error " Invalid Form Key. Please refresh the page and try again. "

**Comment by appinlet** [comment]
@devtactical, kindly try release 2.3.3 per #14 

If the issue still persists, kindly send staging access details and steps to reproduce to support@paygate.co.za.
