### ISSUE TITLE
Place order throws "We could not find "Order" for processing" for paygate module latest version

### ISSUE THREAD

**Issue by AndrewPFBurns** [PayGate/PayWeb_Magento_2#21]
We have installed the latest version of the PayGate module version 2.4.1. We're on Magento 2.4.2 and require this payment method going forward. 

Do you plan on making this module stable for this Mgento version (2.4.2)?

`[2021-05-19 20:05:10] report.CRITICAL: Exception message: We could not find "Order" for processing
Trace: <pre>#1 PayGate\PayWeb\Controller\Redirect\Index->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#2 PayGate\PayWeb\Controller\Redirect\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#3 PayGate\PayWeb\Controller\Redirect\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php:51]
#4 Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#5 PayGate\PayWeb\Controller\Redirect\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#6 PayGate\PayWeb\Controller\Redirect\Index\Interceptor->___callPlugins() called at [generated/code/PayGate/PayWeb/Controller/Redirect/Index/Interceptor.php:23]
#7 PayGate\PayWeb\Controller\Redirect\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#8 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#9 PayGate\PayWeb\Controller\Redirect\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#10 PayGate\PayWeb\Controller\Redirect\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#11 PayGate\PayWeb\Controller\Redirect\Index\Interceptor->___callPlugins() called at [generated/code/PayGate/PayWeb/Controller/Redirect/Index/Interceptor.php:113]
#12 PayGate\PayWeb\Controller\Redirect\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#13 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#14 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#15 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#16 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#17 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#18 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:71]
#19 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#20 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#21 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#22 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#23 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#24 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#25 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:41]
`

**Comment by appinlet** [comment]
Hi @AndrewPFBurns,

The current module version 2.4.1 is supported up to Magento 2.4.3.

In order to debug the above, please kindly submit issue details to support@paygate.co.za.
