### ISSUE TITLE
Provide composer support

### ISSUE THREAD

**Issue by norgeindian** [PayGate/PayWeb_Magento_2#31]
As most of the Magento2 world is now handled via composer, it would be great if you could include a `composer.json` file to make this module available via composer.

**Comment by appinlet** [comment]
@norgeindian this has been actioned. You can install using composer require paygate/paygate-payweb-gateway

**Comment by norgeindian** [comment]
@appinlet , thanks for the including of the `composer.json`.
That's already great. It would be awesome, if you could also define proper dependencies in the `composer.json`, so for example dependencies to other Magento Modules, like defined in the `module.xml`.
This way, composer could do, what it has been made for, and properly handle the dependencies.

**Comment by appinlet** [comment]
@norgeindian we don't make use of non-default libraries, meaning no additional changes are required.

These are default in Magento2:
```
<module name="Magento_Checkout"/>
<module name="Magento_Sales"/>
<module name="Magento_Quote"/>
<module name="Magento_Vault"/>
```

Having a look at other Magento 2 payment gateways, we also don't note them declaring default Magento libraries.
