### ISSUE TITLE
Installation with composer 2.1 the version of extension 2.5.1

### ISSUE THREAD

**Issue by GalichMolodothon** [PayGate/PayWeb_Magento_2#37]
Hello.
I got an error when try to install the PayWeb via composer.
![Selection_305](https://user-images.githubusercontent.com/32126050/189050220-e06f7baf-1c02-486c-beab-f52234767a56.PNG)

Magento CLI 2.4.4-p1
PHP 8.1.6
Ubuntu 20.04.2 LTS
Composer version 2.1.14

The php 8.1 not allowed the library ext-http, but it required in the composer.json for this extension.

**Comment by appinlet** [comment]
@GalichMolodothon version 2.5.1 requires Magento 2.4.5.

**Comment by appinlet** [comment]
@GalichMolodothon use version 2.5.0 for Magento 2.4.5

**Comment by GalichMolodothon** [comment]
The version 2.5.0 require PHP 7.4, it's possible to upload via composer for PHP 8.1

**Comment by appinlet** [comment]
@GalichMolodothon version 2.5.1 supports PHP 8.1, but require Magento 2.4.5.

**Comment by GalichMolodothon** [comment]
@appinlet on my screenshot the error that doesn't connect with the Magento version.
I tested with the Magento 2.4.5 and the same error for command:
**composer require paygate/paygate-payweb-gateway**

The extension has requires, and one of them is PHP library ext-http, which is not supported by PHP 8.1.

**Comment by GalichMolodothon** [comment]
It's the screenshot with the Magento 2.4.5
![Selection_305](https://user-images.githubusercontent.com/32126050/189084774-84155720-c896-46b4-a0b8-628f7639619b.png)

**Comment by GalichMolodothon** [comment]
![Selection_308](https://user-images.githubusercontent.com/32126050/189277059-c63a684d-f6e3-408a-8461-28af21e6ba1e.png)

@appinlet sorry, but this didn't bring forward any changes

**Comment by ChameleonDevil** [comment]
@appinlet 

I want to update your recent changes (https://github.com/PayGate/PayWeb_Magento_2/issues/36), but I have now read in this thread that `v2.5.1` requires `Magento 2.4.5`.  

Am I correct in saying that there is not going to be any compatible version for Magento 2.3 anymore, I would not be able to upgrade to v2.5.1

Magento 2.4 is still in branch `2.4-dev`; and looking at the 1000s of open issues far from 'production ready'.

What about sites that are still running Magento 2.3?  I don't think we are the only ones?

**Comment by appinlet** [comment]
@GalichMolodothon please see https://github.com/PayGate/PayWeb_Magento_2/pull/40.

We have removed this requirement as some servers fail as per the above.

@ChameleonDevil continued in https://github.com/PayGate/PayWeb_Magento_2/issues/38.
