### ISSUE TITLE
Compatibility of newest versions with Magento 2.3x

### ISSUE THREAD

**Issue by ChameleonDevil** [PayGate/PayWeb_Magento_2#38]
@appinlet 

Sorry for highlighting something, but I need clarification:

I want to update your recent changes (https://github.com/PayGate/PayWeb_Magento_2/issues/36), but I have now read in this [thread](https://github.com/PayGate/PayWeb_Magento_2/issues/37) that `v2.5.1` requires `Magento 2.4.5`.  

Am I correct in saying that there is not going to be any compatible version for Magento 2.3 anymore, I would not be able to **upgrade to v2.5.1 or any 'future versions' as Paygate support continues to suggest I do... _and don't understand the compatibility requirements_**

Magento 2.4 is still in branch `2.4-dev`; and looking at the 1000s of open issues far from 'production ready'.

What about sites that are still running Magento 2.3, on `PHP7.3/PHP7.4` ?  I don't think we are the only ones?

**Comment by farmerstevieb** [comment]
I would assume you are correct in your thinking about it not being backwards compatible.
both of those PHP versions, like Magento 2.3 are either end of life or pretty close to it, I would recommend upgrading to 2.4.* line of Magento 2.

**Comment by ChameleonDevil** [comment]
> I would assume you are correct in your thinking about it not being backwards compatible. both of those PHP versions, like Magento 2.3 are either end of life or pretty close to it, I would recommend upgrading to 2.4.* line of Magento 2.

That is unfortunate; I also tried to mention that Magento 2.4 is still in branch `2.4-develop`; I just confirmed again.

There are [over 1,300 open issues](https://github.com/magento/magento2/issues) on Magento 2; just looking at the first two pages 90% of which are **directly related to Magento 2.4**.   

> Do you really have a 'full working production Magento 2.4' installation to make such claims to _recommend upgrading to 2.4*_?

**Comment by farmerstevieb** [comment]
yes, multiple clients are running 2.4.* mainly 2.4.3 and 2.4.4.
We currently have an install on 2.4.4 which has multiple external vendors feeding orders back into it, so yes I am able to make such a claim.
There is, if you look a 2.4.3-release branch and also a 2.5-develop branch.
I agree there are a lot of incompatible changes between the 2 main branches, but, with a good team of developers there should be nothing that is insurmountable.

**Comment by ChameleonDevil** [comment]
> yes, multiple clients are running 2.4.* mainly 2.4.3 and 2.4.4. We currently have an install on 2.4.4 which has multiple external vendors feeding orders back into it, so yes I am able to make such a claim. There is, if you look a 2.4.3-release branch and also a 2.5-develop branch. I agree there are a lot of incompatible changes between the 2 main branches, but, with a good team of developers there should be nothing that is insurmountable.

Thank you for the feedback.
Resources as `developers` are limited where I work, with limited time available. (I am one of them).
We will have a look at a test run with our site and see when migration can happen.

**Comment by appinlet** [comment]
Just a confirmation to the above that v2.5.1 requires Magento 2.4.5.

v2.5.0 unofficially supports Magento 2.3.x -> 2.4.4.
