### ISSUE TITLE
Create a new release, since last release is now outdated

### ISSUE THREAD

**Issue by waleedbasit** [PayGate/PayWeb_Magento_2#41]
Please create a new release, because currently there is still a dependency on **ext-curl** & **ext-http** and this has been fixed in this commit https://github.com/PayGate/PayWeb_Magento_2/commit/c8ada341a2e53e992b6d17f248d9de9a7352363e

**Comment by ChameleonDevil** [comment]
I still wish they would maintain a PHP 7.3 version for Magento 2.3x.  The latest versions completely break on Magento 2.3

**Comment by sprankhub** [comment]
@appinlet, could you please take care of this? Thanks :pray:

**Comment by sprankhub** [comment]
@appinlet!?

**Comment by appinlet** [comment]
@sprankhub we have a new release coming shortly, will update you once released

**Comment by sprankhub** [comment]
Thanks for your feedback. Could you define what "shortly" means? My client is eagerly waiting for it.

**Comment by sprankhub** [comment]
Any update, @appinlet!?

**Comment by appinlet** [comment]
@sprankhub please note that [PayGate Magento plugin v2.5.1 for Magento v2.4.5](https://github.com/PayGate/PayWeb_Magento_2/releases/tag/v2.5.1) does already work on the latest version of Magento and PHP 8.1.

The new release is expected this week, and will also work on the latest version of Magento and PHP 8.1.

[PayGate Magento plugin v2.4.9 for Magento v2.4.3](https://github.com/PayGate/PayWeb_Magento_2/releases/tag/v2.4.9) is the last release for PHP 7.4. 

PHP 7.4 is end of life, and PHP 7.3 reached end of life in 2022. These will not be supported for security reasons.
https://www.php.net/supported-versions.php
