### ISSUE TITLE
PayGate creating multiple orders

### ISSUE THREAD

**Issue by kabadabra** [PayGate/PayWeb_Magento_2#7]
PayGate keeps creating multiple orders while a customer is busy paying via Credit Card or SID. When the customer cancels, the order gets cancelled and the session starts again which is undestandable. However we have a lot of cases where their order is Pending Payment and then then two or three orders later we get a Processing order. 

E.g: https://cl.ly/5e80af3076dd/Image%202019-08-16%20at%2016.19.09.png

Something is causing the session to drop and instead of updating the Pending Payment order to Processing it keeps creating a new order.

**Comment by RBAtkins0n** [comment]
For speedy replies, kindly report issues to support@paygate.co.za.

In this case, it looks as if IPN may not be working correctly. I would suggest reporting the same to the PayGate support team (with the relevant access details) so the issue can be reproduced and debugged accordingly.

**Comment by RBAtkins0n** [comment]
Further on this matter, kindly see #8 which may resolve some issues. You can test IPN and Redirect by toggling the new 'Process Transaction using (IPN)' setting under Admin settings.
